version: 2.1
orbs:
  snyk: snyk/snyk@0.0.10
jobs:
  build-test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'pip install -r requirements.txt'
      - run:
          name: "Install Dev Dependencies"
          command: 'pip install -r requirements-dev.txt'
      - run:
          name: "Test"
          command: 'pytest'
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: false
          token-variable: SNYK_TOKEN
  monitor:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          token-variable: SNYK_TOKEN
  
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test:
          context: SNYK
          filters:
            branches:
              only: 
                - /pull\/[0-9]+/
      - monitor:
          context: SNYK
          requires:
            - build-test
          filters:
            branches:
              only: 
                - master