version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build-test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'pip install -r requirements.txt --user'
      - run:
          name: "Install Dev Dependencies"
          command: 'pip install -r requirements-dev.txt --user'
      - run:
          name: "Test"
          command: '$HOME/.local/bin/pytest'
      - run:
          name: "Lint"
          command: '$HOME/.local/bin/pylint app --ignore-patterns=test_'
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: false
          organization: $SNYK_ORG
          token-variable: SNYK_TOKEN
  build-test-monitor:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'pip install -r requirements.txt --user'
      - run:
          name: "Install Dev Dependencies"
          command: 'pip install -r requirements-dev.txt --user'
      - run:
          name: "Test"
          command: '$HOME/.local/bin/pytest'
      - run:
          name: "Lint"
          command: '$HOME/.local/bin/pylint app --ignore-patterns=test_'
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          project: 'requirements.txt'
          organization: $SNYK_ORG
          token-variable: SNYK_TOKEN


workflows:
  version: 2.1
  #nightly:
  #  triggers:
  #    - schedule:
  #        cron: "0 0 * * *"
  #        filters:
  #          branches:
  #            only:
  #              - master
  #  jobs:
  build-test-monitor:
    when:
      equal: [ "push", << pipeline.parameters.GHA_Event >>]
    jobs:
      - build-test-monitor:
          context: snyk-cs-engineering
          filters:
            branches:
              only: 
                - master
  build-test:
    jobs:
      - build-test:
          context: snyk-cs-engineering
