version: 2.1
orbs:
  snyk: snyk/snyk@0.0.10
jobs:
  build-test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'pip install -r requirements.txt --user'
      - run:
          name: "Install Dev Dependencies"
          command: 'pip install -r requirements-dev.txt --user'
      - run:
          name: "Test"
          command: '$HOME/.local/bin/pytest -v'
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: false
          token-variable: SNYK_TOKEN
  build-test-monitor:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'pip install -r requirements.txt --user'
      - run:
          name: "Install Dev Dependencies"
          command: 'pip install -r requirements-dev.txt --user'
      - run:
          name: "Test"
          command: '$HOME/.local/bin/pytest -v'
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          token-variable: SNYK_TOKEN
  
  
workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test-monitor:
          context: SNYK
          filters:
            branches:
              only: 
                - master
  build-test:
    jobs:
      - build-test:
          context: SNYK
